### ISSUE TITLE
Change curseforge mod tags to support 1.16.5 so curseforge launcher can see the forge version of the pack correctly.

### ISSUE THREAD

**Issue by NighthowlerStudios** [Charles445/DamageTilt#12]
My testing so far has seen it entirely stable on 1.16.5 so why not just make it easier for modpack devs to install it into 1.16.5 packs?

**Comment by Charles445** [comment]
Thought I did that, guess I only did it for fabric.
Added it, hope that works

**Comment by NighthowlerStudios** [comment]
Works great, thanks a bunch
