### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Charles445/DamageTilt#2]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Damage Tilt v0.1.0`

At the time of the crash, I had not taken any damage, but I did have a mob farm running. A zombie was taking damage from a Player Damage Trap from the mod [Dark Utilities](https://www.curseforge.com/minecraft/mc-mods/dark-utilities) when the server crash occured. From taking a glance at the log, a zombie may have had an armor piece on with the Steadfast Enchantment from the [FF's Enchantment](https://www.curseforge.com/minecraft/mc-mods/ffe) mod.
[Crash Report](https://gist.github.com/WenXin20/a3597cf577ed100e70ba30c28813ac5c)

**Comment by Charles445** [comment]
I see, I don't have any failsafe for fake players getting knocked back... oops

Player Trap attacks zombie
Zombie has Steadfast
Zombie gives knockback to the Player Trap's fake player
Fake player has no "connection" to the server
Crash!

I will try to fix this as soon as I can, thank you for the report!

**Comment by Charles445** [comment]
This has been fixed and released with v0.1.1.
 Thanks again!

**Comment by WenXin20** [comment]
Thanks!
